from typing import Tuple, overload
import numpy as np
import numpy.typing as npt
from enum import Enum

class MotorType:
    DM: "MotorType"
    EC: "MotorType"

class RobotConfig:
    def __init__(self, model: str, controller_dt: float) -> None: ...
    joint_pos_min: np.ndarray
    joint_pos_max: np.ndarray
    default_kp: np.ndarray
    default_kd: np.ndarray
    joint_vel_max: np.ndarray
    joint_torque_max: np.ndarray
    ee_vel_max: np.ndarray
    gripper_vel_max: float
    gripper_torque_max: float
    gripper_width: float
    default_gripper_kp: float
    default_gripper_kd: float
    over_current_cnt_max: int
    gripper_open_readout: float
    joint_dof: int
    motor_id: list[int]
    model: str
    motor_type: list[MotorType]
    controller_dt: float

class LogLevel:
    TRACE: "LogLevel"
    DEBUG: "LogLevel"
    INFO: "LogLevel"
    WARNING: "LogLevel"
    ERROR: "LogLevel"
    CRITICAL: "LogLevel"
    OFF: "LogLevel"

class Gain:
    def kp(self) -> npt.NDArray[np.float64]: ...
    def kd(self) -> npt.NDArray[np.float64]: ...
    gripper_kp: float
    gripper_kd: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        kp: npt.NDArray[np.float64],
        kd: npt.NDArray[np.float64],
        gripper_kp: float,
        gripper_kd: float,
    ) -> None: ...
    def __add__(self, other: Gain) -> Gain: ...
    def __mul__(self, scalar: float) -> Gain: ...

class JointState:
    timestamp: float
    gripper_pos: float
    gripper_vel: float
    gripper_torque: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        pos: npt.NDArray[np.float64],
        vel: npt.NDArray[np.float64],
        torque: npt.NDArray[np.float64],
        gripper_pos: float,
    ) -> None: ...
    def __add__(self, other: JointState) -> JointState: ...
    def __mul__(self, scalar: float) -> JointState: ...
    def pos(self) -> npt.NDArray[np.float64]: ...
    def vel(self) -> npt.NDArray[np.float64]: ...
    def torque(self) -> npt.NDArray[np.float64]: ...

class Arx5JointController:
    def __init__(self, model: str, can_name: str) -> None: ...
    def send_recv_once(self) -> None: ...
    def enable_background_send_recv(self) -> None: ...
    def disable_background_send_recv(self) -> None: ...
    def enable_gravity_compensation(self, urdf_path) -> None: ...
    def disable_gravity_compensation(self) -> None: ...
    def set_joint_cmd(self, cmd: JointState) -> None: ...
    def get_joint_cmd(self) -> tuple[JointState, JointState]: ...
    def get_timestamp(self) -> float: ...
    def get_state(self) -> JointState: ...
    def set_gain(self, gain: Gain) -> None: ...
    def get_gain(self) -> Gain: ...
    def get_robot_config(self) -> RobotConfig: ...
    def get_controller_dt_s(self) -> float: ...
    def reset_to_home(self) -> None: ...
    def set_to_damping(self) -> None: ...
    def calibrate_gripper(self) -> None: ...
    def calibrate_joint(self, joint_id: int) -> None: ...
    def set_log_level(self, level: LogLevel) -> None: ...

class EEFState:
    timestamp: float
    gripper_pos: float
    gripper_vel: float
    gripper_torque: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, pose_6d: npt.NDArray[np.float64], gripper_pos: float
    ) -> None: ...
    def __add__(self, other: EEFState) -> EEFState: ...
    def __mul__(self, scalar: float) -> EEFState: ...
    def pose_6d(self) -> npt.NDArray[np.float64]: ...

class Arx5CartesianController:
    def __init__(self, model: str, can_name: str, urdf_path: str) -> None: ...
    def set_eef_cmd(self, cmd: EEFState) -> None: ...
    def get_eef_cmd(self) -> tuple[EEFState, EEFState]: ...
    def get_joint_cmd(self) -> tuple[JointState, JointState]: ...
    def get_eef_state(self) -> EEFState: ...
    def get_joint_state(self) -> JointState: ...
    def get_timestamp(self) -> float: ...
    def set_gain(self, gain: Gain) -> None: ...
    def get_gain(self) -> Gain: ...
    def set_log_level(self, level: LogLevel) -> None: ...
    def get_robot_config(self) -> RobotConfig: ...
    def reset_to_home(self) -> None: ...
    def set_to_damping(self) -> None: ...

class Arx5Solver:
    def __init__(self, urdf_path: str) -> None: ...
    def inverse_dynamics(
        self,
        joint_pos: npt.NDArray[np.float64],
        joint_vel: npt.NDArray[np.float64],
        joint_acc: npt.NDArray[np.float64],
    ) -> npt.NDArray[np.float64]: ...
    def inverse_kinematics(
        self,
        target_pose_6d: npt.NDArray[np.float64],
        current_joint_pos: npt.NDArray[np.float64],
    ) -> Tuple[bool, npt.NDArray[np.float64]]: ...
    def forward_kinematics(
        self, joint_pos: npt.NDArray[np.float64]
    ) -> npt.NDArray[np.float64]: ...
